sonsofnorwaymthoreb/Models/Calendar/CalendarEvent.cs
namespace sonsofnorwaymthoreb.Models.Calendar
{
    public class CalendarEvent
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Date { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
    }
}

sonsofnorwaymthoreb/Models/Home/HomePageEvent.cs
using System;
namespace sonsofnorwaymthoreb.Models.Home
{
    public class HomePageEvent
    {
        public string Title { get; set; }
        public string Date { get; set; }
        public string Description { get; set; }
    }
}

sonsofnorwaymthoreb/Models/PhotoGallery/PhotoGalleryImage.cs
namespace sonsofnorwaymthoreb.Models.PhotoGallery
{
    public class PhotoGalleryImage
    {
        public int Id { get; set; }
        public string FileName { get; set; }
    }
}

sonsofnorwaymthoreb/Models/Vennelag/LutefiskDinner.cs
namespace sonsofnorwaymthoreb.Models.Vennelag
{
    public class LutefiskDinner
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public string Description { get; set; }
    }
}

sonsofnorwaymthoreb/Models/Vennelag/Newsletter.cs
namespace sonsofnorwaymthoreb.Models.Vennelag
{
    public class Newsletter
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Date { get; set; }
        public string Url { get; set; }
    }
}

sonsofnorwaymthoreb/Models/Vennelag/ProgramOrActivity.cs
namespace sonsofnorwaymthoreb.Models.Vennelag
{
    public class ProgramOrActivity
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
    }
}

sonsofnorwaymthoreb/ViewModels/Calendar/CalendarViewModel.cs
using System.Collections.Generic;
using sonsofnorwaymthoreb.Models.Calendar;

namespace sonsofnorwaymthoreb.ViewModels.Calendar
{
    public class CalendarViewModel
    {
        public IEnumerable<CalendarEvent> CalendarEvents { get; set; }
    }
}

sonsofnorwaymthoreb/ViewModels/Home/HomeViewModel.cs
using sonsofnorwaymthoreb.Models.Home;

namespace sonsofnorwaymthoreb.ViewModels.Home
{
    public class HomeViewModel
    {
        public HomePageEvent HomePageEvent { get; set; }
    }
}

sonsofnorwaymthoreb/ViewModels/PhotoGallery/PhotoGalleryViewModel.cs
using System.Collections.Generic;
using sonsofnorwaymthoreb.Models.PhotoGallery;

namespace sonsofnorwaymthoreb.ViewModels.PhotoGallery
{
    public class PhotoGalleryViewModel
    {
        public IEnumerable<PhotoGalleryImage> PhotoGalleryImages { get; set; }
    }
}

sonsofnorwaymthoreb/ViewModels/Vennelag/VennelagViewModel.cs
using System.Collections.Generic;
using sonsofnorwaymthoreb.Models.Vennelag;

namespace sonsofnorwaymthoreb.ViewModels.Vennelag
{
    public class VennelagViewModel
    {
        public IEnumerable<LutefiskDinner> LutefiskDinners { get; set; }
        public IEnumerable<ProgramOrActivity> ProgramsAndActivities { get; set; }
        public IEnumerable<Newsletter> Newsletters { get; set; }
    }
}

sonsofnorwaymthoreb/Controllers/AboutUsController.cs
using Microsoft.AspNetCore.Mvc;

namespace sonsofnorwaymthoreb.Controllers
{
    public class AboutUsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

sonsofnorwaymthoreb/Controllers/AppExceptionController.cs
using Microsoft.AspNetCore.Mvc;

namespace sonsofnorwaymthoreb.Controllers
{
    public class AppExceptionController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

sonsofnorwaymthoreb/Controllers/CalendarController.cs
using Microsoft.AspNetCore.Mvc;
using sonsofnorwaymthoreb.Services.Calendar;
using sonsofnorwaymthoreb.ViewModels.Calendar;

namespace sonsofnorwaymthoreb.Controllers
{
    public class CalendarController : Controller
    {
        private ICalendarData _calendarData;

        public CalendarController(
            ICalendarData calendarData)
        {
            _calendarData = calendarData;
        }

        public IActionResult Index() {
            var model = new CalendarViewModel();

            model.CalendarEvents = _calendarData.GetAll();

            return View(model);
        }
    }
}

sonsofnorwaymthoreb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using sonsofnorwaymthoreb.Services.Home;
using sonsofnorwaymthoreb.ViewModels.Home;

namespace sonsofnorwaymthoreb.Controllers
{
    public class HomeController : Controller
    {
        private IHomePageEventData _homePageEventData;

        public HomeController(IHomePageEventData homePageEventData)
        {
            _homePageEventData = homePageEventData;
        }

        public IActionResult Index()
        {
            var model = new HomeViewModel();

            model.HomePageEvent = _homePageEventData.Get();

            return View(model);
        }
    }
}

sonsofnorwaymthoreb/Controllers/PhotoGalleryController.cs
using Microsoft.AspNetCore.Mvc;
using sonsofnorwaymthoreb.Services.PhotoGallery;
using sonsofnorwaymthoreb.ViewModels.PhotoGallery;

namespace sonsofnorwaymthoreb.Controllers
{
    public class PhotoGalleryController : Controller
    {
        private IPhotoGalleryImageData _photoGalleryImageData;

        public PhotoGalleryController(
            IPhotoGalleryImageData photoGalleryImageData)
        {
            _photoGalleryImageData = photoGalleryImageData;
        }

        public IActionResult Index()
        {
            var model = new PhotoGalleryViewModel();

            model.PhotoGalleryImages = _photoGalleryImageData.GetAll();

            return View(model);
        }
    }
}

sonsofnorwaymthoreb/Controllers/ProgramsAndActivitiesController.cs
using Microsoft.AspNetCore.Mvc;

namespace sonsofnorwaymthoreb.Controllers
{
    public class ProgramsAndActivitiesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

sonsofnorwaymthoreb/Controllers/ScholarshipController.cs
using Microsoft.AspNetCore.Mvc;

namespace sonsofnorwaymthoreb.Controllers
{
    public class ScholarshipController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
    }
}

sonsofnorwaymthoreb/Controllers/VennelagController.cs
using Microsoft.AspNetCore.Mvc;
using sonsofnorwaymthoreb.Services;
using sonsofnorwaymthoreb.Services.Vennelag;
using sonsofnorwaymthoreb.ViewModels.Vennelag;

namespace sonsofnorwaymthoreb.Controllers
{
    public class VennelagController : Controller
    {
        private IProgramsAndActivitiesData _programsAndActivitiesData;
        private ILutefiskDinnersData _lutefiskDinnersData;
        private INewsletterData _newsletterData;

        public VennelagController(
            IProgramsAndActivitiesData programsAndActivitiesData,
            ILutefiskDinnersData lutefiskDinnersData,
            INewsletterData newsletterData)
        {
            _programsAndActivitiesData = programsAndActivitiesData;
            _lutefiskDinnersData = lutefiskDinnersData;
            _newsletterData = newsletterData;
        }

        public IActionResult Index()
        {
            var model = new VennelagViewModel();

            model.ProgramsAndActivities = _programsAndActivitiesData.GetAll();
            model.LutefiskDinners = _lutefiskDinnersData.GetAll();
            model.Newsletters = _newsletterData.GetAll();

            return View(model);
        }
    }
}

sonsofnorwaymthoreb/Views/AboutUs/Index.cshtml
@{
    ViewData["Title"] = "About Us";
}

<h2 class="section-header">Who We Are</h2>
<div class="section-header">
    <div class="vennelag-section vennelag-text">
        <p>
            The Sons of Norway is an international organization with a local connection in Mt. Horeb, WI.
            Additional lodges can be found across Canada, Norway, and the remainder of the United States of America.
            There are 51,600 members as of December, 2017.
            One goal of the Sons of Norway is to connect with communities and their residents by celebrating the customs and heritage of the Norwegian people.
            Vennelag Lodge (the Circle of Friends) holds meetings with either a social or cultural focus in the months of January through June, and from September through December.
            As a fraternal organization, Vennelag Lodge also offers optional financial benefits to its members.
        </p>
        <br/>
        <p>
            Two large culinary events are shared with the public every year.
            A summer Kaffe Stue (coffee/lunch room) is held every July in conjunction with Mt. Horeb’s Annual Art Fair.
            Members prepare a Høst Frokost or fall breakfast the first Saturday of October.
            In addition, a popular Norwegian Baking Workshop is held the first Saturday of November and is open to all, including youth 9 years of age and older with adult supervision.
            A Juletrefest or Christmas Tree Festival occurs annually on the first Saturday in December.
        </p>
        <br/>
        <p>
            Activities for children include riding on our Viking float in area parades, sponsorship at the Barnebirke or Children’s Ski Race held prior to the American Birkebeiner every February in Hayward, WI, and a two-week summer Norwegian heritage camp called Masse Moro, which means “lots of fun”!
            This camp is held at Beaver Creek Reserve near Fall Creek, WI.
            For more information, select: <a href="http://www.massemoro.org" target="_blank">www.massemoro.org</a>.
            Members receive discounts for camp attendance from both the local and district levels of the organization, making this unique camp experience very affordable.
        </p>
        <br/>
        <p>
            As youth age, college scholarships, as well as travel opportunities are offered.
            A post-secondary opportunity to attend a folk high school in Norway is also possible.
            For more information, view the website: <a href="http://www.SofN.com" target="_blank">www.SofN.com</a>, and click Foundation on the top ribbon then select scholarships.
            A program called Norway Connects also pairs young adults with businesses in Norway that can launch their careers.
            Attendance at a Norwegian university is an option for adults.
            Some prerequisites apply.
            Vennelag members have attended the University of Oslo and the University of Bergen.
        </p>
        <br/>
        <p>
            Vennelag Lodge is a vibrant and active community partner, enriching the lives of area citizens through it philanthropic service and support.
            Should you need more information about Vennelag Lodge, please contact: Cheryl Wille-Schlesser, Lodge President, at: <a href="mailto:rogrcher@mhtc.net" target="_top">rogrcher@mhtc.net</a> or call: 608-219-4464.
        </p>
    </div>
</div>

<h2 class="section-header">History of Vennelag</h2>
<div class="section-header">
    <div class="vennelag-section vennelag-text">
        <p>
            Sons of Norway Lodge #5-513 was chartered in Mt. Horeb, Wisconsin by Hilmen E. Kjorlie, President of the Supreme Lodge on November 19, 1971, with 83 charter members.
            The first official meeting was held on January 27, 1971, when the name for the new lodge was chosen.
            "Vennelag" means "Circle of Friends".
            By the time the charter was closed, 164 members had signed.
        </p>
        <br/>
        <p>
            From the start, Vennelag Lodge members have participated in many community events such as the Summer Frolic and the former Song of Norway.
            They have welcomed visitors from Norway for many years.
            The Lodge has worked closely with the Mt. Horeb Area Historical Society to preserve Norwegian artifacts from area families.
            They were led by George Sievers whose involvement with the Lodge spanned over 30 years.
        </p>
        <br/>
        <p>
            Numerous cultural activities have been implemented including bunad construction classes, knitting classes, Hardanger embroidery lessons, and rosemaling instruction.
            A book club also began. The S.S. Vennelag, a Viking ship float has sailed through area parades for approximately 3 decades, helping to put Mt. Horeb on everyone's radar!
        </p>
        <br/>
        <p>
            Since 1979 a summer Kaffee Stue has been held every July. It has had numerous locations but now calls the Mt. Horeb Community Center, 107 N. Grove Street, its home.
            Over the course of time, a fall breakfast was added to the culinary line-up on the first Saturday in October.
            A Norwegian Baking Workshop was instituted, meeting the needs of many area residents.
            Recently, the Lodge began a lefse fundraiser which is held just prior to Christmas.
            Other fundraisers help the Ledge to fund high school and heritage camp scholarhips, and they provide money for noteworthy needs and projects.
        </p>
        <br/>
        <p>
            Vennelag members have been active in Fifth District affairs, sending delegates to biennial conventions, and hosting the District 5 Board for dinner and for breakfast over years.
            Numerous individuals have also served in leadership positions on District 5 Board, and one person also served on the International Board of Directors.
            Vennelag has sent delegates to International Conventions, too.
        </p>
        <br/>
        <p>
            Today, Vennelag is a vibrant and growing lodge, meeting the #Growing to2020 goal set by the International Board of Directors in 2017.
            The Lodge continues to fill the need felt in 1971...for an organization that could express the desires and interests of local Norwegian-Americans who now call the Mt. Horeb area home.
        </p>
        <br/>
        <p>
            Submitted by: Cheryl Wille-Schlesser, Lodge President, January, 2018.
        </p>
    </div>
</div>

<h2 class="section-header">Executive Committee</h2>
<div class="vennelag-section">
    <table class="table">
        <tbody class="vennelag-text">
            <tr>
                <td class="td-left">
                    <strong>President:</strong>
                </td>
                <td>
                    <p>Cheryl Wille-Schlesser<br/></p>
                </td>
                <td>
                    <small>
                        Address: 200 Beth Circle, Mount Horeb, WI 53572<br/>
                        Phone: 608-219-4464<br/>
                        E-Mail: <a href="mailto:rogrcher@mhtc.net" target="_top">rogrcher@mhtc.net</a>
                    </small>
                </td>
                <td>
                    <img class="img-responsive visible-lg" src="~/images/about-us/cheryl.jpg" style="height: 120px;"/>
                </td>
            </tr>
            <tr>
                <td class="td-left">
                    <strong>Vice President / Membership Secretary:</strong>
                </td>
                <td>
                    <p>Carolyn Johnson (mentoring Jean Grindle)<br/></p>
                </td>
                <td>
                    <small>
                        Address: 938 Fritz Road, Belleville, WI 53508<br/>
                        Phone: 608-424-3149<br/>
                        E-Mail: <a href="mailto:cmj@chorus.net" target="_top">cmj@chorus.net</a>
                    </small>
                </td>
                <td>
                    <img class="img-responsive visible-lg" src="~/images/about-us/carolyn.jpg" style="height: 120px;"/>
                </td>
            </tr>
            <tr>
                <td class="td-left">
                    <strong>Counselor:</strong>
                </td>
                <td colspan="3">
                    <p>Chuck Mørkri</p>
                </td>
            </tr>
            <tr>
                <td class="td-left">
                    <strong>Secretary:</strong>
                </td>
                <td colspan="3">
                    <p>Rita Schraepfer, an Assistant Secretary is welcome.</p>
                </td>
            </tr>
            <tr>
                <td class="td-left">
                    <strong>Treasurer:</strong>
                </td>
                <td colspan="3">
                    <p>Tamiko Clary, an Assistant Treasurer is welcome.</p>
                </td>
            </tr>
        </tbody>
    </table>
</div>

<h2 class="section-header">Program Directors</h2>
<div class="vennelag-section">
    <table class="table">
        <tbody class="vennelag-text">
            <tr>
                <td class="td-left">
                    <strong>Social Director:</strong>
                </td>
                <td>
                    <p>Allen Watrud</p>
                </td>
            </tr>
            <tr>
                <td class="td-left">
                    <strong>Food Chairman:</strong>
                </td>
                <td>
                    <p>Ann Walser (mentoring Mary Gullickson-Krantz)</p>
                </td>
            </tr>
            <tr>
                <td class="td-left">
                    <strong>Cultural Director:</strong>
                </td>
                <td>
                    <p>Tiffany Schwoerer</p>
                </td>
            </tr>
            <tr>
                <td class="td-left">
                    <strong>Sports and Recreation Director:</strong>
                </td>
                <td>
                    <p>Davi Penne</p>
                </td>
            </tr>
            <tr>
                <td class="td-left">
                    <strong>Foundation Director:</strong>
                </td>
                <td>
                    <p>Harley Skjervem</p>
                </td>
            </tr>
            <tr>
                <td class="td-left">
                    <strong>Youth Directors:</strong>
                </td>
                <td>
                    <p>Michelle and Kelly Skeels</p>
                </td>
            </tr>
        </tbody>
    </table>
</div>

<h2 class="section-header">Supporting Directors</h2>
<div class="vennelag-section">
    <table class="table">
        <tbody class="vennelag-text">
            <tr>
                <td class="td-left">
                    <strong>Trustees / Auditors:</strong>
                </td>
                <td>
                    <p>Arthur Ness, John Eberhardt, David Andersen</p>
                </td>
            </tr>
            <tr>
                <td class="td-left">
                    <strong>Publicity Director:</strong>
                </td>
                <td>
                    <p>Mary Gullickson-Krantz</p>
                </td>
            </tr>
            <tr>
                <td class="td-left">
                    <strong>Newsletter Editor:</strong>
                </td>
                <td>
                    <p>Arlene Watrud-Krueger</p>
                </td>
            </tr>
            <tr>
                <td class="td-left">
                    <strong>Webmaster (not an elected position):</strong>
                </td>
                <td>
                    <p>Evan Ellis</p>
                </td>
            </tr>
            <tr>
                <td class="td-left">
                    <strong>Historian / Scrapbook:</strong>
                </td>
                <td>
                    <p>Aldeen Fjelstad</p>
                </td>
            </tr>
            <tr>
                <td class="td-left">
                    <strong>Musician:</strong>
                </td>
                <td>
                    <p>Eric Albrecht (Nathan Albrecht and Brenda Albrecht will assist).<br/>
                    Lora Lee will serve as mentor.</p>
                </td>
            </tr>
            <tr>
                <td class="td-left">
                    <strong>Marshal & Assistant Marshal:</strong>
                </td>
                <td>
                    <p>Positions will be assigned before any special lodge event such as Installation of Officers.</p>
                </td>
            </tr>
            <tr>
                <td class="td-left">
                    <strong>Greeters:</strong>
                </td>
                <td>
                    <p>Those who are on the set-up crew for a monthly meeting will also serve as greeters for that day.</p>
                </td>
            </tr>
            <tr>
                <td class="td-left">
                    <strong>Frokost and Kaffe Stue Committees:</strong>
                </td>
                <td>
                    <p>All members of Vennelag Lodge<br/>
                    (These events would not be successful without the input and support of all members.)</p>
                </td>
            </tr>
        </tbody>
    </table>
</div>

sonsofnorwaymthoreb/Views/AppException/Index.cshtml
<div class="vennelag-section">
    <h2 class="text-danger">Something went wrong.</h2>
    <h4 class="text-danger">We have notified the web master!</h4>
</div>

sonsofnorwaymthoreb/Views/Calendar/Index.cshtml
@model sonsofnorwaymthoreb.ViewModels.Calendar.CalendarViewModel

@{
    ViewData["Title"] = "Calendar";
}

<div class="vennelag-section">
    <div class="text-left">
        <h2 class="section-header">Calendar</h2>
        <table class="table">
            <tbody class="vennelag-text">
                @foreach (var calendarEvent in Model.CalendarEvents) {
                    <tr>
                        <td>
                            <h4 style="font-size: 1.5em;">@calendarEvent.Date</h4>
                            @if (calendarEvent.Title != null) {
                                <h4 style="line-height: 1.4;">@calendarEvent.Title</h4>
                            }
                            <br/>
                            @calendarEvent.Description
                            @if (calendarEvent.Url != null) {
                                <a href="@calendarEvent.Url" target="_blank">
                                    Read more about it here!
                                </a>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

sonsofnorwaymthoreb/Views/PhotoGallery/Index.cshtml
@model sonsofnorwaymthoreb.ViewModels.PhotoGallery.PhotoGalleryViewModel

@{
    ViewData["Title"] = "Photo Gallery";
}

<div style="margin-top: 40px;">
    <ul class="row ul-assist spec center-block">
        @foreach (var photoGalleryImage in Model.PhotoGalleryImages) {
            <li class="img-fluid ul-li-assist col-lg-3 col-md-4 col-sm-6 col-xs-12" data-index="@photoGalleryImage.Id">
                <img class="ul-li-img-assist" src="@photoGalleryImage.FileName"/>
            </li>
        }
    </ul>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

sonsofnorwaymthoreb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sons of Norway Mt. Horeb</title>

    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.11';
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
        
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
  
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Home</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Vennelag" asp-action="Index">Vennelag</a></li>
                    <li><a asp-area="" asp-controller="Calendar" asp-action="Index">Calendar</a></li>
                    <li><a asp-area="" asp-controller="Scholarship" asp-action="Index">Scholarship</a></li>                            
                    <li><a asp-area="" asp-controller="PhotoGallery" asp-action="Index">Photo Gallery</a></li>
                    <li><a asp-area="" asp-controller="AboutUs" asp-action="Index">About Us</a></li>
                </ul>
            </div>
        </div>
    </nav>  
        
    <div class="container body-content">
        @RenderBody()
        <hr>
        <footer>
            <div class="row">
                <div class="col-md-3 col-sm-12 text-center section-header">
                    <p>&copy; 2018 - Sons of Norway Mt. Horeb</p>
                </div>
                <div class="col-md-7 col-sm-0"></div>
                <div class="col-md-2 col-sm-12">
                    <img class="footer-logo img-responsive center-block" src="~/images/logo.png"/>
                </div>
            </div>
        </footer>
    </div>
    
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

sonsofnorwaymthoreb/Views/Vennelag/Index.cshtml
@model sonsofnorwaymthoreb.ViewModels.Vennelag.VennelagViewModel

@{
    ViewData["Title"] = "Vennelag";
}

<div class="row" style="margin-top:30px;">
    <div class="col-md-7 vennelag-section hidden-md hidden-sm hidden-xs">
        <img class="img-responsive" src="~/images/vennelag/water.jpg"/>
    </div>
    <div class="col-lg-5 vennelag-section">
        <div class="well text-left">
            <div class="well-assist-2">
                <h2 class="section-header">Newsletters</h2>
                <table class="table">
                    <tbody>
                        @foreach (var newsletter in Model.Newsletters) {
                            <tr>
                                <td>
                                    <strong>@newsletter.Date</strong>
                                </td>
                                <td>
                                    <a href="@newsletter.Url" target="_blank">
                                        @newsletter.Title
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="vennelag-section">
    <div class="text-left">
        <h2 class="section-header">Join Vennelag</h2>
        <p style="font-size:18px;">
            Contrary to the name Sons of Norway, you don't have to be male or even Norwegian to join. 
            <br><br>
            The primary requirement for membership in Vennelag 5-513 is to have an interest in Norwegian cultural and heritage.
            You are invited to attend any of our programs or special events to find out more about the benefits offered by Sons of Norway.
            <br><br>
            <a href="http://sonsofnorway5.com/join/" target="_blank">Download a membership application form or sign up online</a>
        </p>
    </div>
</div>

<div class="vennelag-section">
    <div class="text-left">
        <h2 class="section-header">Programs and Activities</h2>
        <table class="table">
            <tbody class="vennelag-text">
                @foreach (var programOrActivity in Model.ProgramsAndActivities) {
                    <tr>
                        <td class="td-left">
                            <strong>@programOrActivity.Name</strong>
                        </td>
                        <td>
                            @programOrActivity.Description
                            @if (programOrActivity.Url != null) {
                                <a href="@programOrActivity.Url" target="_blank">
                                    Read more about it here!
                                </a>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<div class="vennelag-section">
    <div class="text-left">
        <h2 class="section-header">Lutefisk Dinners</h2>
        <table class="table">
            <tbody class="vennelag-text">
                @foreach (var lutefiskDinner in Model.LutefiskDinners) {
                    <tr>
                        <td class="td-left">
                            <strong>@lutefiskDinner.Date</strong>
                        </td>
                        <td>
                            @lutefiskDinner.Description
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>